name: 2GP Beta Test
on:
    push:
        branches:
            - main
jobs:
    feature-test:
        name: "Beta Test"
        uses: muselab-d2x/d2x/.github/workflows/beta-2gp.yml@main
        secrets:
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"
            gh-email: "${{ secrets.GH_EMAIL }}"
            github-token: "${{ secrets.GITHUB_TOKEN }}"